### ISSUE TITLE
Juniper compatibility

### ISSUE THREAD

**Issue by toxinu** [pmitros/AnimationXBlock#2]
Hi there,

I wanted to know if your xBlock is already Juniper (Python 3 and Django 2.2) compatible and if not, is there any plan to update it for Juniper? Or are you open to contributions?

Thanks.

cc @pmitros

**Comment by pmitros** [comment]
Hi,

1) No clue if it's compatible, but I'd assume not. 
2) Definitely open to contributions.

**Comment by toxinu** [comment]
Thanks for your reply @pmitros. 😃
